// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'become-a-backer': string;
  'container': string;
  'item': string;
}
export const cssExports: CssExports;
export default cssExports;
