// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'biography': string;
  'container': string;
  'description': string;
  'icon': string;
  'name': string;
}
export const cssExports: CssExports;
export default cssExports;
