// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'apps': string;
  'button': string;
  'buttons': string;
  'container': string;
  'device-motion-event': string;
  'name': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
