// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'appContainer': string;
  'apps': string;
  'menu': string;
  'name': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
