// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'border': string;
  'character': string;
  'cloud': string;
  'cloud-1': string;
  'cloud-10': string;
  'cloud-11': string;
  'cloud-12': string;
  'cloud-13': string;
  'cloud-2': string;
  'cloud-3': string;
  'cloud-4': string;
  'cloud-5': string;
  'cloud-6': string;
  'cloud-7': string;
  'cloud-8': string;
  'cloud-9': string;
  'container': string;
  'logo': string;
  'parallax': string;
  'parallax-js': string;
  'rainbow': string;
}
export const cssExports: CssExports;
export default cssExports;
