// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'c': string;
  'c1': string;
  'c10': string;
  'c11': string;
  'c12': string;
  'c13': string;
  'c14': string;
  'c2': string;
  'c3': string;
  'c4': string;
  'c5': string;
  'c6': string;
  'c7': string;
  'c8': string;
  'c9': string;
  'character': string;
  'container': string;
  'fixed': string;
  'logo': string;
  'parallax': string;
  'parallaxs': string;
  'rainbow': string;
}
export const cssExports: CssExports;
export default cssExports;
