// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'article': string;
  'articles': string;
  'biography': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
