// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'appContainer': string;
  'apps': string;
  'article': string;
  'articles': string;
  'booth': string;
  'container': string;
  'description': string;
  'item': string;
  'menu': string;
  'name': string;
  'tag': string;
  'tags': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
